# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Carro' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Carro

  pod 'LNTools_fyh/LNViewExtension'
  pod 'HandyJSON'
  pod 'SnapKit'
  
  target 'CarroTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CarroUITests' do
    # Pods for testing
  end

end
